### ISSUE TITLE
Loop header IDs should be created deterministically

### ISSUE THREAD

**Issue by benjholla** [EnSoftCorp/jimple-toolbox-commons#1]
The DLI algorithm should produce the same loop header identifiers for the same application when recomputed again (even if the Atlas index is different). Currently the analysis results are the same, but the loop identifiers change.

**Comment by atamrawi** [comment]
AFAIK, we need to sort the loop headers based on source correspondence before assigning them IDs.

In DecompiledLoopIdentification class, the  loopHeaders collection needs to be sorted based on source correspondence.

**Comment by benjholla** [comment]
Yea, I think I might even do something a little more robust and qualify the IDs by contains relationships (ex: Class->Method->Loop1,Loop2,...). So that way if the methods are reordered the analysis result is the same.

**Comment by benjholla** [comment]
Implemented in cee6d76ad47906c73a0304841cdd64535902788e. Loop headers are assigned in alphabetical order of source correspondence file and then by offset.
